export const variabless = {
    "BodyFontFamily": "\"Lekton\", Helvetica",
  "BodyFontSize": 14,
  "BodyFontStyle": "normal",
  "BodyFontWeight": 400,
  "BodyLetterSpacing": 0,
  "BodyLineHeight": "normal",
  "CardShadow": "0px 4px 12px 0px rgba(0, 0, 0, 0.25)",
  "Cardstroke": "rgba(255, 255, 255, 0.12)",
  "HeaderFontFamily": "\"Lekton\", Helvetica",
  "HeaderFontSize": 20,
  "HeaderFontStyle": "normal",
  "HeaderFontWeight": 700,
  "HeaderLetterSpacing": 0,
  "HeaderLineHeight": "normal",
  "LabelFontFamily": "\"Lekton\", Helvetica",
  "LabelFontSize": 12,
  "LabelFontStyle": "normal",
  "LabelFontWeight": 400,
  "LabelLetterSpacing": 0,
  "LabelLineHeight": "normal",
  "SubheadingFontFamily": "\"Lekton\", Helvetica",
  "SubheadingFontSize": 16,
  "SubheadingFontStyle": "normal",
  "SubheadingFontWeight": 700,
  "SubheadingLetterSpacing": 0,
  "SubheadingLineHeight": "normal",
  "VariableCollectionDark": "rgba(24, 24, 24, 1)",
  "VariableCollectionH1": "rgba(255, 252, 95, 1)",
  "VariableCollectionH2": "rgba(30, 226, 121, 1)",
  "VariableCollectionH3": "rgba(27, 126, 255, 1)",
  "VariableCollectionHighlight": "rgba(231, 73, 0, 1)",
  "VariableCollectionMedium": "rgba(28, 31, 30, 1)"
}